// website-react-spa/src/components/social-handles/SocialHandlesBand.jsx
import React from 'react'

import { Container } from '@mui/material'
import Box from '@mui/material/Box'

import SocialHandle from './SocialHandle'

export default function SocialHandlesBand() {
  return (
    <Box
      sx={{
        flexGrow: 1,
        pt: 2,
        pb: 2,
        justifyContent: 'space-between',
      }}
    >
      <Container sx={{ textAlign: 'center', justifyContent: 'space-between' }}>
        <SocialHandle social='GITHUB' url='https://github.com/rimaz523' />
        <SocialHandle social='MEDIUM' url='https://rimazmohommed523.medium.com' />
        <SocialHandle social='LINKEDIN' url='https://www.linkedin.com/in/rimazmohommed' />
        <SocialHandle
          social='STACKOVERFLOW'
          url='https://stackoverflow.com/users/4546132/rimaz-mohommed'
        />
        <SocialHandle social='TWITTER' url='https://twitter.com/rimaz_mohommed' />
      </Container>
    </Box>
  )
}

// website-angular-spa/src/app/components/social-handles-band/social-handles-band.component.ts
import { Component } from '@angular/core'
import { MatDividerModule } from '@angular/material/divider'
import { MatIconModule } from '@angular/material/icon'
import { SocialHandleComponent } from '../social-handle/social-handle.component'
import { ISocialHandle } from '@models/social-handle.model'
import { NgFor } from '@angular/common'

@Component({
  selector: 'rmz-social-handles-band',
  imports: [MatDividerModule, MatIconModule, SocialHandleComponent, NgFor],
  templateUrl: './social-handles-band.component.html',
  styleUrl: './social-handles-band.component.scss',
})
export class SocialHandlesBandComponent {
  socialHandles: ISocialHandle[]

  constructor() {
    this.socialHandles = [
      {
        name: 'Github',
        url: 'https://github.com/rimaz523',
        displayOrder: 1,
      },
      {
        name: 'Medium',
        url: 'https://rimazmohommed523.medium.com',
        displayOrder: 2,
      },
      {
        name: 'Linkedin',
        url: 'https://www.linkedin.com/in/rimazmohommed',
        displayOrder: 3,
      },
      {
        name: 'Stackoverflow',
        url: 'https://stackoverflow.com/users/4546132/rimaz-mohommed',
        displayOrder: 4,
      },
      {
        name: 'Twitter',
        url: 'https://twitter.com/rimaz_mohommed',
        displayOrder: 5,
      },
    ]
  }

  getOrderedSocialHandles(): ISocialHandle[] {
    return this.socialHandles.sort((a, b) => a.displayOrder - b.displayOrder)
  }
}

<div class="social-handles-section">
  <mat-divider></mat-divider>
  <div class="handles">
    <rmz-social-handle
      *ngFor="let socialHandle of getOrderedSocialHandles()"
      [socialHandle]="socialHandle"></rmz-social-handle>
  </div>
</div>
