// website-angular-spa/src/stories/button.component.ts
import { CommonModule } from '@angular/common'
import { Component, Input, Output, EventEmitter } from '@angular/core'

@Component({
  selector: 'rmz-button',
  standalone: true,
  imports: [CommonModule],
  template: ` <button
    type="button"
    (click)="Click.emit($event)"
    [ngClass]="classes"
    [ngStyle]="{ 'background-color': backgroundColor }">
    {{ label }}
  </button>`,
  styleUrls: ['./button.css'],
})
export class ButtonComponent {
  /** Is this the principal call to action on the page? */
  @Input()
  primary = false

  /** What background color to use */
  @Input()
  backgroundColor?: string

  /** How large should the button be? */
  @Input()
  size: 'small' | 'medium' | 'large' = 'medium'

  /**
   * Button contents
   *
   * @required
   */
  @Input()
  label = 'Button'

  /** Optional click handler */
  @Output()
  Click = new EventEmitter<Event>()

  public get classes(): string[] {
    const mode = this.primary ? 'storybook-button--primary' : 'storybook-button--secondary'

    return ['storybook-button', `storybook-button--${this.size}`, mode]
  }
}

// website-react-spa/src/stories/Button.jsx
import React from 'react'

import PropTypes from 'prop-types'

import './button.css'

/**
 * Primary UI component for user interaction
 */
export const Button = ({ primary, backgroundColor, size, label, ...props }) => {
  const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary'
  return (
    <button
      type='button'
      className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
      style={backgroundColor && { backgroundColor }}
      {...props}
    >
      {label}
    </button>
  )
}

Button.propTypes = {
  /**
   * Is this the principal call to action on the page?
   */
  primary: PropTypes.bool,
  /**
   * What background color to use
   */
  backgroundColor: PropTypes.string,
  /**
   * How large should the button be?
   */
  size: PropTypes.oneOf(['small', 'medium', 'large']),
  /**
   * Button contents
   */
  label: PropTypes.string.isRequired,
  /**
   * Optional click handler
   */
  onClick: PropTypes.func,
}

Button.defaultProps = {
  backgroundColor: null,
  primary: false,
  size: 'medium',
  onClick: undefined,
}
